name: Sync Fork

on:
  schedule:
    - cron: '0 7 * * *' # everyday 7am UTC
  workflow_dispatch: # on button click

jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: anuraghazra/github-readme-stats
          target_repository: infinitepower18/github-readme-stats
          upstream_branch: master
          target_branch: master
